### ISSUE TITLE
Linux build failure with gdal version 3.3.2

### ISSUE THREAD

**Issue by rhabacker** [vsg-dev/vsgGIS#10]
Building vsgGIS on openSUSE Leap 15.2 with gdal 3.3.2 let the build fail with the following error message:
```
[100%] Linking CXX executable ../../bin/vsggis
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/libgdal.so: undefined reference to `opj_encoder_set_extra_options'
```

**Comment by robertosfield** [comment]
On Mon, 6 Sept 2021 at 10:33, Ralf Habacker ***@***.***>
wrote:

> Building vsgGIS on openSUSE Leap 15.2 with gdal 3.3.2 let the build fail
> with the following error message:
>
> [100%] Linking CXX executable ../../bin/vsggis
> /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/libgdal.so: undefined reference to `opj_encoder_set_extra_options'
>
>
I have 3.2.2 installed on my Ubuntu 20.04 system without problems, so
perhaps something changed with 3.3.2, perhaps the CMake find GDAL isn't
sufficient for your config.

Currently the vsgGIS/src/vsgGIS/CMakeLists.txt only uses the GDAL_LIBRARY
var, and looking at my /usr/share/cmake-3.18

Could you have a look at CMake's usr/share/cmake-version/Modules
/FindGDAL.cmake and it has a GDAL_LIBRARY and a GDAL_LIBRARIES var that
just maps to GDAL_LIBRARY.  Could you check your FindGDAL.cmake to see if
GDAL_LIBRARIES includes the lib that might provide
opj_encoder_set_extra_options?


vsgGIS/src/vsgGIS/CMakeLists.txt uses

**Comment by rhabacker** [comment]
```
 grep -rn GDAL_LIB /usr/share/cmake/Modules/FindGDAL.cmake 
25:``GDAL_LIBRARIES``
35:``GDAL_LIBRARY``
134:find_library(GDAL_LIBRARY
155:    REQUIRED_VARS GDAL_LIBRARY GDAL_INCLUDE_DIR)
160:        IMPORTED_LOCATION "${GDAL_LIBRARY}"
164:set(GDAL_LIBRARIES ${GDAL_LIBRARY})
```

**Comment by rhabacker** [comment]
This [bug report](https://www.mail-archive.com/gdal-dev@lists.osgeo.org/msg35514.html) may be related

**Comment by rhabacker** [comment]
The issue ssems specific to the mentioned version as I just checked to build vsgFramework with gdal 3.0.4 without any issue.

**Comment by robertosfield** [comment]
On Thu, 12 May 2022 at 13:37, Ralf Habacker ***@***.***>
wrote:

> The issue ssems specific to the mentioned version as I just checked to
> build vsgFramework with gdal 3.0.4 without any issue.
> Message ID: ***@***.***>


So is it safe to close this Issue now?

**Comment by rhabacker** [comment]
I also did a successful build with a newer version (libgdal30-3.4.2-2.5) on [Tumbleweed](https://build.opensuse.org/package/show/home:rhabacker:branches:games/vsgGIS)  so yes.

**Comment by robertosfield** [comment]
Great to hear, nothing better than an Issue resolving itself if you leave it long enough :-)
